# OUTPUT_LANG_INDEX start from 0
generator-localization:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=12otuvwbxPtkSXdWBDlxtgpwnlaCQuQFy_FVsVm6Lf2Y GID_ID=Sheet1 OUTPUT_FOLDER=../src/locales/en/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=12otuvwbxPtkSXdWBDlxtgpwnlaCQuQFy_FVsVm6Lf2Y GID_ID=Sheet1 OUTPUT_FOLDER=../src/locales/cn/common.json


	
